//### AUTOMATICALLY GENERATED BY src/covarianceMatrixStudy.cpp ###//
//### DATASET: TT_FCNC-TtoHJ_aThadronic_HToaa_eta_hct-MadGraph5-pythia8
#ifndef _COV_MATRIX_H_
#define _COV_MATRIX_H_

#include <TMatrixD.h>
#include <TVectorD.h>

#define W_BOSON_MASS 80.379 //GeV
#define TOP_QUARK_MASS 173.0 //GeV

inline
double Chi2_calculator_simple(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - W_BOSON_MASS;
    vec_mass(1) = t_mass - TOP_QUARK_MASS;
    TMatrixD matrix(2,2);
    matrix(0,0) = 293.63; matrix(0,1) =   0.00;
    matrix(1,0) =   0.00; matrix(1,1) = 756.77;
    return matrix.Invert()*vec_mass*vec_mass;
}

inline
double Chi2_calculator_modified(double w_mass, double t_mass){
    TVectorD vec_mass(2);
    vec_mass(0) = w_mass - W_BOSON_MASS;
    vec_mass(1) = t_mass - TOP_QUARK_MASS;
    TMatrixD matrix(2,2);
    matrix(0,0) = 293.63; matrix(0,1) = 311.26;
    matrix(1,0) = 311.26; matrix(1,1) = 756.77;
    return matrix.Invert()*vec_mass*vec_mass;
}

inline
double Chi2_calculator_improved(double w_mass, double t_mass, double fcnc_top_mass){
    TVectorD vec_mass(3);
    vec_mass(0) = w_mass - W_BOSON_MASS;
    vec_mass(1) = t_mass - TOP_QUARK_MASS;
    vec_mass(2) = fcnc_top_mass - TOP_QUARK_MASS;
    TMatrixD matrix(3,3);
    matrix(0,0) = 293.63; matrix(0,1) = 311.26; matrix(0,2) = -50.42;
    matrix(1,0) = 311.26; matrix(1,1) = 756.77; matrix(1,2) = 313.96;
    matrix(2,0) = -50.42; matrix(2,1) = 313.96; matrix(2,2) = 2367.25;
    return matrix.Invert()*vec_mass*vec_mass;
}

#endif
